# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5df730f96abb56d6f396b6e04ab82644"
name = "TapNTrust Insights"
application_url = "https://tapntrust.com"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_orders,write_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["orders/updated"]
uri = "https://go.tapntrust.com/api/shopify/webhooks/orders-updated"
