/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: ad6f46babd498f8e92b67ceb34f5a71c)
// Runtime types generated with workerd@1.20260908.1 2026-09-11 nodejs_compat
interface __BaseEnv_Env {
	DB: D1Database;
	AUTH_BASE_URL: "https://go.tapntrust.com";
	AUTH_FROM_EMAIL: "contact@tapntrust.com";
	STOREFRONT_ORIGIN: "https://tapntrust.com";
	SHOPIFY_SHOP_DOMAIN: "iz8qif-0j.myshopify.com";
	SHOPIFY_ADMIN_API_VERSION: "2026-07";
	SHOPIFY_INSIGHTS_VARIANT_ID: "gid://shopify/ProductVariant/48192855376003";
	SHOPIFY_INSIGHTS_INTRO_SELLING_PLAN_ID: "gid://shopify/SellingPlan/2791899267";
	SHOPIFY_INSIGHTS_STANDARD_SELLING_PLAN_ID: "gid://shopify/SellingPlan/2791899267";
	ADMIN_API_TOKEN: string;
	ZEPTOMAIL_API_KEY: string;
	GOOGLE_PLACES_API_KEY: string;
	SHOPIFY_CLIENT_ID: string;
	SHOPIFY_CLIENT_SECRET: string;
	SHOPIFY_INSIGHTS_INTRO_DISCOUNT_CODE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_BASE_URL" | "AUTH_FROM_EMAIL" | "STOREFRONT_ORIGIN" | "SHOPIFY_SHOP_DOMAIN" | "SHOPIFY_ADMIN_API_VERSION" | "SHOPIFY_INSIGHTS_VARIANT_ID" | "SHOPIFY_INSIGHTS_INTRO_SELLING_PLAN_ID" | "SHOPIFY_INSIGHTS_STANDARD_SELLING_PLAN_ID" | "ADMIN_API_TOKEN" | "ZEPTOMAIL_API_KEY" | "GOOGLE_PLACES_API_KEY" | "SHOPIFY_CLIENT_ID" | "SHOPIFY_CLIENT_SECRET" | "SHOPIFY_INSIGHTS_INTRO_DISCOUNT_CODE">> {}
}

// Begin runtime types
/*! *****************************************************************************
Copyright (c) Cloudflare. All rights reserved.
Copyright (c) Microsoft Corporation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
***************************************************************************** */
/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
declare var onmessage: never;
/**
 * The **`DOMException`** interface represents an abnormal event (called an exception) that occurs as a result of calling a method or accessing a property of a web API. This is how error conditions are described by web APIs.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException)
 */
declare class DOMException extends Error {
    constructor(message?: string, name?: string);
    /**
     * The **`message`** read-only property of the DOMException interface returns a string representing a message or description associated with the given error name.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException/message)
     */
    readonly message: string;
    /**
     * The **`name`** read-only property of the DOMException interface returns a string that contains one of the strings associated with an error name.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException/name)
     */
    readonly name: string;
    /**
     * The **`code`** read-only property of the DOMException interface returns one of the legacy error code constants, or 0 if no matching legacy error code exists.
     * @deprecated
     */
    readonly code: number;
    static readonly INDEX_SIZE_ERR: number;
    static readonly DOMSTRING_SIZE_ERR: number;
    static readonly HIERARCHY_REQUEST_ERR: number;
    static readonly WRONG_DOCUMENT_ERR: number;
    static readonly INVALID_CHARACTER_ERR: number;
    static readonly NO_DATA_ALLOWED_ERR: number;
    static readonly NO_MODIFICATION_ALLOWED_ERR: number;
    static readonly NOT_FOUND_ERR: number;
    static readonly NOT_SUPPORTED_ERR: number;
    static readonly INUSE_ATTRIBUTE_ERR: number;
    static readonly INVALID_STATE_ERR: number;
    static readonly SYNTAX_ERR: number;
    static readonly INVALID_MODIFICATION_ERR: number;
    static readonly NAMESPACE_ERR: number;
    static readonly INVALID_ACCESS_ERR: number;
    static readonly VALIDATION_ERR: number;
    static readonly TYPE_MISMATCH_ERR: number;
    static readonly SECURITY_ERR: number;
    static readonly NETWORK_ERR: number;
    static readonly ABORT_ERR: number;
    static readonly URL_MISMATCH_ERR: number;
    static readonly QUOTA_EXCEEDED_ERR: number;
    static readonly TIMEOUT_ERR: number;
    static readonly INVALID_NODE_TYPE_ERR: number;
    static readonly DATA_CLONE_ERR: number;
}
